import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/single-use/Navbar/Navbar";
import AuthProvider from "@/components/single-use/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} main_color`}>
        <AuthProvider>
          <Navbar></Navbar>
          <main className="w-full h-auto">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
